### PR TITLE
feat(operator): greaterThanOrEqual operator

### PR DESCRIPTION
**Pull request by km4**
PR for https://github.com/xFAANG/askql/issues/135

### CODE REVIEW

**Comment by czerwinskilukasz1** [comment]
@km4 , just a hint: use [this message](https://github.com/xFAANG/askql/pull/114#issuecomment-642231103) and [this file](https://github.com/xFAANG/askql/blob/master/src/askscript/__tests__/00-documentation-examples/documentation01-complete_example.test.ask) as an inspiration.

**Comment by km4** [comment]
sure :) @czerwinskilukasz1 you have some generator for *.ask, *.askjson, *.askcode files?

**Comment by czerwinskilukasz1** [comment]
@km4 , following [Marcin's comment in another issue](https://github.com/xFAANG/askql/pull/114#issuecomment-642231103), please rename the resource to `greaterThanOrEqual`.

**Comment by czerwinskilukasz1** [comment]
@km4 , as for test, I discovered that the syntax in the example test file I sent you a link to, doesn't really work yet. 
Could you please watch changes in my PR for lessThanOrEqual and when it's approved, create similar tests?

**Comment by km4** [comment]
I think it's all.

**Pull request merged**
