### PR TITLE
test(askscript): added a test for assigning a value in an inner scope

### PR DESCRIPTION
**Pull request by czerwinskilukasz1**
Related to issue #129

### CODE REVIEW

**Comment by mhagmajer** [comment]
Thanks for posting this PR! This test should pass once I fix the underlying issue.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 I included this change already in https://github.com/xFAANG/askql/pull/199, would you like to add another test for scoping? ;)

**Comment by czerwinskilukasz1** [comment]
It seems you added my files to your changes. Closing this PR.

**Comment by mhagmajer** [comment]
That's right. Thanks @czerwinskilukasz1!

**Pull request closed without merging**
