### PR TITLE
refactor(askcode): Simplify call(get('get'),'n') in generated AskCode

### PR DESCRIPTION
**Pull request by km4**

### CODE REVIEW

**Comment by mhagmajer** [comment]
@km4 any updates here? Please let me know if you have any questions

**Comment by km4** [comment]
get some problem with understanding this calculated/converted code.

Example:

*ask
```
ask() {
    let n
    n = 3
   return n
}
```

return  *askcode
```
ask(let('n'),assign('n',3),return(call(get('get'),'n')))
```

and if I paste on our playground all its fine, but if I change askcode to 
```
ask(let('n'),assign('n',3),return(call(get('n'))))
```

got error `Error: Cannot call 3`

**Comment by km4** [comment]
> get some problem with understanding this calculated/converted code.
> 
> Example:
> 
> *ask
> 
> ```
> ask() {
>     let n
>     n = 3
>    return n
> }
> ```
> 
> return *askcode
> 
> ```
> ask(let('n'),assign('n',3),return(call(get('get'),'n')))
> ```
> 
> and if I paste on our playground all its fine, but if I change askcode to
> 
> ```
> ask(let('n'),assign('n',3),return(call(get('n'))))
> ```
> 
> got error `Error: Cannot call 3`

ok now I see, `call(get(get` the change to only `get(`

**Comment by czerwinskilukasz1** [comment]
@km4 , the main idea for fixing this ticket is to fix the code which **generates** the .askcode files: https://github.com/xFAANG/askql/blob/master/src/test.jest.testRunner.ts

So just a find-and-replace in the generated .askcode files wouldn't be enough. 
After you fix the generator, you can just easily remove all the .askcode files in the project, run `npm test` and they will be regenerated using your fixed code.

**Comment by czerwinskilukasz1** [comment]
Hey, @km4 . Would you like more pointers for this issue?

**Comment by km4** [comment]
@czerwinskilukasz1 
Yes, I debug this generates process and I find the only problem in askCodeToSource function.

source
```
ask {
        let a =1
return a
}
```
askFormatted
```
ask() {
  let a = 1
  return get('a')
}
```

askCode `const askCode = parseAskScript(askFormatted);`
```
AskCode {
  name: 'ask',
  params: [
    AskCode { name: 'let', params: [Array] },
    AskCode { name: 'return', params: [Array] }
  ]
}
```

askSourceCode `const askCodeSource = askCodeToSource(askCode);`
```
ask(let('a',1),return(call(get('get'),'a')))
```

Then the problem is on https://github.com/xFAANG/askql/blob/master/src/askcode/lib/AskCode.ts#L76 ?

**Comment by km4** [comment]
@czerwinskilukasz1 or @mhagmajer can you check this ^ ?

**Comment by mhagmajer** [comment]
@km4 yes, that looks about right. If you're still working on that, please reopen the PR or comment on the issue #200

**Pull request closed without merging**
