### PR TITLE
fix(tests): remove false positives

### LINKED ISSUE #148: Fix false positive tests
Some test have invalid `expectedResult`. This issue is about auditing all tests and fixing those.

### PR DESCRIPTION
**Pull request by mhagmajer**
Close #148

### CODE REVIEW

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , how do we know these are all files where tests didn't work propertly?  I think there were some .ask test files, which were not constructed properly too.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 these are all that I have found, we also have tests for remote that were disabled (tracked separately here: https://github.com/xFAANG/askql/issues/98). If you now about more we can add them here or in a new issue.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , there was a number of tests you altered in 25 commits during your coding spree around 3am on May 25.
One of them is basics16c-const_without_value.ts.notImplemented from commit f228690006acd3f44887a72ecab9b9140b6ec320, which was supposed to fail when executing the .ask file, but you changed it to accepting it (see screenshot), which is incorrect. 

Please review all the commits created that night and resolve the issues.


image

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , what's the progress on this issue?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 `const a` and `let b` are fine and they create a new value equal to `empty`

**Pull request merged**
